import React, { useState, useEffect } from 'react';
import { FileText, Download, TrendingUp, Award, Users, CheckCircle, BarChart3, ShieldCheck, Printer } from 'lucide-react';
import api from '../../services/api';
import { ReportsData } from '../../types';
import ScrollReveal from '../../components/common/ScrollReveal';
import TiltCard from '../../components/3d/TiltCard';
import { playClickSound } from '../../utils/soundEffects';

const AdminReportsPage: React.FC = () => {
  const [reports, setReports] = useState<ReportsData | null>(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    const fetchReports = async () => {
      try {
        const res = await api.get('/admin/reports');
        setReports(res.data);
      } catch (err) {
        console.error(err);
      } finally {
        setLoading(false);
      }
    };
    fetchReports();
  }, []);

  const handleExportPDF = () => {
    playClickSound();
    if (!reports) return;

    const reportContent = `
================================================================================
NEXORA SYSTEM OPERATIONS & ANALYTICS REPORT
Generated On: ${new Date().toLocaleString()}
Generated By: System Administrator Governance
================================================================================

1. EXECUTIVE METRICS SUMMARY
--------------------------------------------------------------------------------
- Total Campus Registrations: ${reports.total_registrations}
- Verified Event Attendances: ${reports.total_attendances}
- Official E-Certificates Issued: ${reports.total_certificates}

2. EVENT CATEGORY BREAKDOWN
--------------------------------------------------------------------------------
${reports.events_summary.map(item => `- ${item.category.toUpperCase()}: ${item.count} Published Events`).join('\n')}

3. SECURITY & COMPLIANCE
--------------------------------------------------------------------------------
- Real-Time Waitlist Queue Operations: ACTIVE
- 3D QR Code Token Verification: ENFORCED
- System Status: 100% OPERATIONAL

================================================================================
END OF OFFICIAL NEXORA SYSTEM ANALYTICS REPORT
================================================================================
    `.trim();

    const blob = new Blob([reportContent], { type: 'text/plain;charset=utf-8;' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.setAttribute('download', `Nexora_System_Analytics_Report_${new Date().toISOString().slice(0, 10)}.pdf`);
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);

    // Also trigger browser print to PDF
    window.print();
  };

  if (loading) return <div className="text-center py-16 text-slate-500 font-bold">Generating system analytics reports...</div>;

  return (
    <div className="max-w-5xl mx-auto space-y-8 relative z-10">
      <ScrollReveal direction="up">
        <div className="flex flex-col sm:flex-row justify-between items-start sm:items-center gap-4">
          <div>
            <h1 className="text-3xl font-black text-slate-900 dark:text-slate-100 font-poppins">Nexora Analytics & Reports</h1>
            <p className="text-xs text-slate-600 dark:text-slate-400 mt-1">Participation metrics, category breakdowns, and certificate issuance trends</p>
          </div>

          <button
            onClick={handleExportPDF}
            className="bg-emerald-600 hover:bg-emerald-700 text-white font-bold text-xs px-6 py-3 rounded-2xl shadow-lg transition flex items-center gap-2"
          >
            <Printer className="w-4 h-4" />
            <span>Export Official PDF Report</span>
          </button>
        </div>
      </ScrollReveal>

      {/* Top Metrics Cards */}
      <div className="grid grid-cols-1 sm:grid-cols-3 gap-6">
        <ScrollReveal direction="up" delay={50}>
          <TiltCard maxTilt={8}>
            <div className="bg-white dark:bg-slate-900/90 p-6 rounded-3xl border border-slate-200 dark:border-slate-800 shadow-md space-y-2">
              <div className="flex justify-between items-center text-blue-600 dark:text-blue-400">
                <Users className="w-6 h-6" />
                <span className="text-[10px] font-black uppercase text-slate-400">Total Signups</span>
              </div>
              <h3 className="text-3xl font-black text-slate-900 dark:text-slate-100">{reports?.total_registrations || 0}</h3>
              <p className="text-xs text-slate-500">Confirmed registrations across all fests</p>
            </div>
          </TiltCard>
        </ScrollReveal>

        <ScrollReveal direction="up" delay={100}>
          <TiltCard maxTilt={8}>
            <div className="bg-white dark:bg-slate-900/90 p-6 rounded-3xl border border-slate-200 dark:border-slate-800 shadow-md space-y-2">
              <div className="flex justify-between items-center text-emerald-500">
                <ShieldCheck className="w-6 h-6" />
                <span className="text-[10px] font-black uppercase text-slate-400">Verified Attendances</span>
              </div>
              <h3 className="text-3xl font-black text-slate-900 dark:text-slate-100">{reports?.total_attendances || 0}</h3>
              <p className="text-xs text-slate-500">QR check-ins verified at entrance</p>
            </div>
          </TiltCard>
        </ScrollReveal>

        <ScrollReveal direction="up" delay={150}>
          <TiltCard maxTilt={8}>
            <div className="bg-white dark:bg-slate-900/90 p-6 rounded-3xl border border-slate-200 dark:border-slate-800 shadow-md space-y-2">
              <div className="flex justify-between items-center text-amber-500">
                <Award className="w-6 h-6" />
                <span className="text-[10px] font-black uppercase text-slate-400">Certificates Issued</span>
              </div>
              <h3 className="text-3xl font-black text-slate-900 dark:text-slate-100">{reports?.total_certificates || 0}</h3>
              <p className="text-xs text-slate-500">Official digital e-credentials</p>
            </div>
          </TiltCard>
        </ScrollReveal>
      </div>

      {/* Category Breakdown Card */}
      <ScrollReveal direction="up" delay={200}>
        <div className="bg-white dark:bg-slate-900/90 p-6 sm:p-8 rounded-3xl border border-slate-200 dark:border-slate-800 shadow-md space-y-6">
          <div className="flex items-center gap-3 pb-4 border-b border-slate-100 dark:border-slate-800">
            <div className="p-2.5 bg-blue-500/10 text-blue-600 dark:text-blue-400 rounded-xl">
              <BarChart3 className="w-5 h-5" />
            </div>
            <div>
              <h3 className="text-base font-bold text-slate-900 dark:text-slate-100 font-poppins">Events Distribution by Category</h3>
              <p className="text-xs text-slate-500 dark:text-slate-400">Live active event listings breakdown</p>
            </div>
          </div>

          <div className="grid grid-cols-2 sm:grid-cols-3 gap-4">
            {reports?.events_summary.map((cat, idx) => (
              <div key={idx} className="p-4 rounded-2xl bg-slate-50 dark:bg-slate-950/60 border border-slate-200 dark:border-slate-800 space-y-1">
                <span className="text-[10px] font-extrabold uppercase text-blue-600 dark:text-blue-400 tracking-wider">{cat.category}</span>
                <p className="text-2xl font-black text-slate-900 dark:text-slate-100 font-poppins">{cat.count}</p>
                <p className="text-[10px] text-slate-400">Active Listings</p>
              </div>
            ))}
          </div>
        </div>
      </ScrollReveal>
    </div>
  );
};

export default AdminReportsPage;
